resources:
  - nifi/cert-manager.yaml
  - nifi/configmap.yaml
  - nifi/service.yaml
  - nifi/statefulset.yaml
  - zookeeper/configmap.yaml
  - zookeeper/statefulset.yaml
  - zookeeper/service-headless.yaml
  - zookeeper/service.yaml
