---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nifi-secret-reader
  namespace: nifi
automountServiceAccountToken: false
---
apiVersion: v1
kind: Secret
metadata:
  name: nifi-secret-reader-token
  namespace: nifi
  annotations:
    kubernetes.io/service-account.name: nifi-secret-reader
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nifi-secret-reader
  namespace: nifi
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nifi-secret-reader
  namespace: nifi
subjects:
  - kind: ServiceAccount
    name: nifi-secret-reader
roleRef:
  kind: Role
  name: nifi-secret-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nifi-ca
  namespace: nifi
spec:
  isCA: true
  duration: 87660h0m0s
  renewBefore: 5m1s
  commonName: nifi-ca.nifi.svc.cluster.local
  subject:
    organizationalUnits:
      - NIFI
  secretName: nifi-ca
  privateKey:
    algorithm: RSA
    size: 2048
    rotationPolicy: Always
  issuerRef:
    name: nifi
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nifi-0
  namespace: nifi
spec:
  duration: 2160h0m0s
  commonName: nifi-0.nifi-headless.nifi.svc.cluster.local
  subject:
    organizationalUnits:
      - NIFI
  secretName: nifi-0
  privateKey:
    rotationPolicy: Always
  usages:
    - digital signature
    - content commitment
    - key encipherment
    - data encipherment
    - key agreement
    - server auth
    - client auth
  dnsNames:
    - localhost
    - nifi.nifi.svc
    - nifi.nifi.svc.cluster.local
    - nifi-0.nifi-headless.nifi.svc
    - nifi-0.nifi-headless.nifi.svc.cluster.local
  issuerRef:
    name: nifi-ca
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nifi-1
  namespace: nifi
spec:
  duration: 2160h0m0s
  commonName: nifi-1.nifi-headless.nifi.svc.cluster.local
  subject:
    organizationalUnits:
      - NIFI
  secretName: nifi-1
  privateKey:
    rotationPolicy: Always
  usages:
    - digital signature
    - content commitment
    - key encipherment
    - data encipherment
    - key agreement
    - server auth
    - client auth
  dnsNames:
    - localhost
    - nifi.nifi.svc
    - nifi.nifi.svc.cluster.local
    - nifi-1.nifi-headless.nifi.svc
    - nifi-1.nifi-headless.nifi.svc.cluster.local
  issuerRef:
    name: nifi-ca
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nifi-2
  namespace: nifi
spec:
  duration: 2160h0m0s
  commonName: nifi-2.nifi-headless.nifi.svc.cluster.local
  subject:
    organizationalUnits:
      - NIFI
  secretName: nifi-2
  privateKey:
    rotationPolicy: Always
  usages:
    - digital signature
    - content commitment
    - key encipherment
    - data encipherment
    - key agreement
    - server auth
    - client auth
  dnsNames:
    - localhost
    - nifi.nifi.svc
    - nifi.nifi.svc.cluster.local
    - nifi-2.nifi-headless.nifi.svc
    - nifi-2.nifi-headless.nifi.svc.cluster.local
  issuerRef:
    name: nifi-ca
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: nifi
  namespace: nifi
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: nifi-ca
  namespace: nifi
spec:
  ca:
    secretName: nifi-ca
