---
apiVersion: v1
kind: Service
metadata:
  name: nifi-headless
  labels:
    app: "nifi"
    chart: "nifi-1.2.1"
    release: "nifi"
    heritage: "Helm"
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 8443
      name: https
    - port: 6007
      name: cluster
    - port: 10000
      name: site-to-site
  selector:
    app: "nifi"
    release: "nifi"
---
apiVersion: v1
kind: Service
metadata:
  name: nifi
  labels:
    app: "nifi"
    chart: "nifi-1.2.1"
    release: "nifi"
    heritage: "Helm"
spec:
  type: ClusterIP
  ports:
    - port: 8443
      name: https
      targetPort: 8443
      nodePort:
    - port: 10000
      name: site-to-site
      targetPort: 10000
  selector:
    app: nifi
    release: nifi
